name: my-first-github-action 
on: [push]
jobs:
  miprimerjob: # Nombre del job
    runs-on: ubuntu-latest # Linux
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install -g bats
    - run: bats -v
  misegundojob: # Nombre del job
    needs: miprimerjob
    runs-on: ubuntu-latest # Linux
    steps:
    - run: echo 'Hola Mundo'
